version: 0.0
os: linux
files:
  - source: /
    destination: /usr/bin/spring_app
    file_exists_behavior: OVERWRITE
permissions:
  - object: /usr/bin/spring_app
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 700
    type:
      - file
hooks:
  BeforeInstall:
    - location: before_install.sh
      timeout: 300
      runas: ec2-user
  ApplicationStop:
    - location: application_stop.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: application_start.sh
      timeout: 300
      runas: ec2-user